name: KBOT-CICD
on: 
  push:
    branches:
      - develop
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test
        run: make test
      - name: Log in to registry
        run: echo "${{ secrets.SECRET_KBOT_2 }}" | docker login ghcr.io -u $ --password-stdin        
      - name: Build&Push
        env:
          APP: "kbot"
        run: make image push